name: Validation

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  pdk-validate:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Run pdk validate
      uses: addnab/docker-run-action@v3
      with:
        image: puppet/pdk
        options: -v ${{ github.workspace }}:/module -w /module
        run: |
          apt-get update && apt-get install build-essential -y
          pdk validate --parallel

  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Run pdk test unit
      uses: addnab/docker-run-action@v3
      with:
        image: puppet/pdk
        options: -v ${{ github.workspace }}:/module -w /module
        run: |
          apt-get update && apt-get install build-essential -y
          pdk test unit -v
